const allGames = [
    {name:'Tylko pytania', music:false, minAct:4, group:1, dynamic:false},
    {name:'Historia po słowie', music:false, minAct:2, group:1, dynamic:false},
    {name:'Oskarowa rola', music:false, minAct:2, group:1, dynamic:true},
    {name:'Dwójka w grze', music:false, minAct:3, group:1, dynamic:true},
    {name:'Więcej-mniej', music:false, minAct:2, group:1, dynamic:true},
    {name:'Shoty', music:false, minAct:2, group:1, dynamic:false},
    {name:'Freezy', music:false, minAct:3, group:1, dynamic:true},
    {name:'Rewolwer', music:false, minAct:4, group:1, dynamic:false},
    {name:'Telezakupy', music:false, minAct:2, group:1, dynamic:false},
    {name:'Martwy głos - historia prawdziwa', music:false, minAct:2, group:1, dynamic:false},
    {name:'To brzmi jak ta piosenka', music:true, minAct:2, group:1, dynamic:true},
    {name:'Konferencja', music:false, minAct:3, group:1, dynamic:false},
    {name:'Książki', music:false, minAct:2, group:1, dynamic:false},
    {name:'Barman', music:true, minAct:2, group:1, dynamic:true},
    {name:'Dyrygent', music:false, minAct:3, group:1, dynamic:false},
    {name:'Alfabet', music:false, minAct:2, group:1, dynamic:false},
    {name:'Wyjście na słowo', music:false, minAct:3, group:1, dynamic:true},
    {name:'Ławka emocji', music:false, minAct:4, group:1, dynamic:false},
    {name:'2x dwie głowy', music:false, minAct:4, group:1, dynamic:false},
    {name:'Pierwsza i ostatnia kwestia', music:false, minAct:3, group:1, dynamic:false},
    {name:'Superbohaterowie', music:false, minAct:3, group:1, dynamic:true},
    {name:'Śmierć w minutę', music:false, minAct:2, group:1, dynamic:true},
    {name:'Żywa sceneria', music:false, minAct:4, group:1, dynamic:true},
    {name:'Wykrywacz kłamstw', music:false, minAct:2, group:1, dynamic:false},
    {name:'Pstryk', music:false, minAct:2, group:1, dynamic:false},
    {name:'Komentatorzy zwykłych czynności', music:false, minAct:4, group:1, dynamic:true},
    {name:'Randka w ciemno', music:false, minAct:4, group:2, dynamic:false},
    {name:'Przyjęcie', music:false, minAct:4, group:2, dynamic:true},
    {name:'Dziwni prezenterzy', music:false, minAct:4, group:2, dynamic:false},
    {name:'5-4-3-2-1', music:false, minAct:3, group:3, dynamic:true},
    {name:'60-30-15-5', music:false, minAct:2, group:3, dynamic:true},
    {name:'Kwestie z kieszeni', music:false, minAct:2, group:4, dynamic:true},
    {name:'Kapitan', music:false, minAct:1, group:4, dynamic:false},
    {name:'Dubbing krzyżowy', music:false, minAct:4, group:5, dynamic:false},
    {name:'Dubbing filmowy', music:false, minAct:3, group:5, dynamic:false},
    {name:'LOW', music:false, minAct:3, group:6, dynamic:false},
    {name:'Spóźnienie do pracy', music:false, minAct:3, group:6, dynamic:true},
    {name:'Madam Zelda', music:false, minAct:4, group:6, dynamic:true},
    {name:'Wywiad z tłumaczeniem dla niemych', music:false, minAct:3, group:6, dynamic:true},
    {name:'Wywiad z rękoma', music:false, minAct:4, group:7, dynamic:false},
    {name:'Szara eminencja', music:false, minAct:2, group:7, dynamic:false},
    {name:'Wywiad wstecz', music:false, minAct:2, group:7, dynamic:false},
    {name:'Dwugłowy ekspert', music:false, minAct:2, group:7, dynamic:false},
    {name:'Ślepy replay', music:false, minAct:4, group:8, dynamic:true},
    {name:'Głuchy replay', music:false, minAct:4, group:8, dynamic:true},
    {name:'Switch 3-osobowy', music:false, minAct:3, group:9, dynamic:true},
    {name:'Siedź-stój-pochyl się', music:false, minAct:3, group:9, dynamic:true},
    {name:'Ruch, dźwięk, mowa', music:false, minAct:0, group:9, dynamic:true},
    {name:'Dotyk znaczy mowa', music:false, minAct:2, group:9, dynamic:false},
    {name:'Wielokrotność charakteru', music:false, minAct:3, group:9, dynamic:false},
    {name:'Wehikuł czasu', music:false, minAct:2, group:10, dynamic:true},
    {name:'DVD', music:false, minAct:4, group:10, dynamic:true},
    {name:'Do przodu, do tyłu', music:false, minAct:2, group:10, dynamic:true},
    {name:'Marionetki', music:false, minAct:2, group:11, dynamic:true},
    {name:'Trupy', music:false, minAct:3, group:11, dynamic:true},
    {name:'Style filmowe', music:false, minAct:2, group:12, dynamic:true},
    {name:'Hollywoodzki reżyser', music:false, minAct:2, group:12, dynamic:true},
    {name:'Zmiana(ding)', music:false, minAct:2, group:12, dynamic:true},
    {name:'Paolo Coelho', music:false, minAct:2, group:13, dynamic:false},
    {name:'Coś ty powiedział?', music:false, minAct:2, group:13, dynamic:false},
    {name:'Co chcesz przez to powiedzieć?', music:false, minAct:2, group:13, dynamic:false},
    {name:'Serwis', music:false, minAct:2, group:14, dynamic:false},
    {name:'Poradnia małżeńska', music:false, minAct:3, group:14, dynamic:false},
    {name:'Podwójne naprowadzenie', music:false, minAct:2, group:14, dynamic:false},
    ];

    export default allGames